version: "3.9"

services:
  jaeger:
    image: jaegertracing/all-in-one:1.55
    ports:
      - 4317:4317
      - 16686:16686
  prometheus:
    image: prom/prometheus:v2.51.0
    ports:
      - 9090:9090
