name: CI
on:
  push:
    branches:
      - master
  pull_request:
concurrency: ${{ github.workflow }}-${{ github.ref }}
env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/base
      - run: pnpm build
      - run: pnpm lint
      - run: pnpm run test --concurrency=5
