name: Release
on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
    branches:
      - master
concurrency: ${{ github.workflow }}-${{ github.ref }}
env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
jobs:
  changesets:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/base
      - run: pnpm build
      - uses: changesets/action@v1
        with:
          publish: pnpm build && pnpm exec changesets publish
        env:
          GITHUB_TOKEN: ${{ github.token }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/base
      - run: pnpm build --filter docs
      - uses: actions/configure-pages@v4
      - uses: actions/upload-pages-artifact@v3
        with:
          path: packages/docs/build
      - uses: actions/deploy-pages@v4
